---
- name: Create and Configure a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Write meta-data file
      copy:
        content: |
          # cloud-config
          instance-id: {{ vm_name }}
          local-hostname: {{ vm_name }}
        dest: "/var/lib/libvirt/images/meta-data"

    - name: Create a qcow2 file for VM
      shell: >
        sudo qemu-img create -f qcow2 -F qcow2 -o backing_file=/var/lib/libvirt/images/jammy-server-cloudimg-amd64.img /var/lib/libvirt/images/{{ vm_name }}.qcow2
      args:
        executable: /bin/bash

    - name: Resize the qcow2 file to 10G
      command: >
        sudo qemu-img resize /var/lib/libvirt/images/{{ vm_name }}.qcow2 10G
    
    - name: Create cidata.iso for cloud-init
      shell: >
        sudo genisoimage -output /var/lib/libvirt/images/{{ vm_name }}-cidata.iso -volid cidata -joliet -rock /var/lib/libvirt/images/user-data /var/lib/libvirt/images/meta-data
      args:
        executable: /bin/bash
    
    - name: Execute virt-install to create the VM
      shell: >
        sudo virt-install --virt-type kvm --name {{ vm_name }}
        --ram {{ ram }} --vcpus {{ cpu }} --os-variant ubuntu22.04
        --disk path=/var/lib/libvirt/images/{{ vm_name }}.qcow2,format=qcow2
        --disk path=/var/lib/libvirt/images/{{ vm_name }}-cidata.iso,device=cdrom
        --noautoconsole --import --network network='{{ network_name }}'
      args:
        executable: /bin/bash

    - name: Attach interface to VM
      become: true
      command: >
        sudo virsh attach-interface --type bridge --model virtio {{ vm_name }} --source {{ ovs_bridge_name  }}
         args:
           executable: /bin/bash
