---
- name: VM Delete Operations
  hosts: localhost
  gather_facts: no
  vars:
    vm_name: "{{ vm_name }}"
  tasks:
    - name: Shutdown VM
      command: "sudo virsh shutdown {{ vm_name }}"
      ignore_errors: yes

    - name: Undefine VM
      command: "sudo virsh undefine {{ vm_name }}"
      ignore_errors: yes
